//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OC_Calculus_ConsoleClient.OperationsArithmetiquesService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="OperationsArithmetiquesService.IOperationsArithmetiques")]
    public interface IOperationsArithmetiques {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOperationsArithmetiques/Plus", ReplyAction="http://tempuri.org/IOperationsArithmetiques/PlusResponse")]
        double Plus(double nb1, double nb2);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOperationsArithmetiques/Plus", ReplyAction="http://tempuri.org/IOperationsArithmetiques/PlusResponse")]
        System.Threading.Tasks.Task<double> PlusAsync(double nb1, double nb2);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOperationsArithmetiques/Moins", ReplyAction="http://tempuri.org/IOperationsArithmetiques/MoinsResponse")]
        double Moins(double nb1, double nb2);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOperationsArithmetiques/Moins", ReplyAction="http://tempuri.org/IOperationsArithmetiques/MoinsResponse")]
        System.Threading.Tasks.Task<double> MoinsAsync(double nb1, double nb2);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOperationsArithmetiques/Diviser", ReplyAction="http://tempuri.org/IOperationsArithmetiques/DiviserResponse")]
        double Diviser(double nb1, double nb2);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOperationsArithmetiques/Diviser", ReplyAction="http://tempuri.org/IOperationsArithmetiques/DiviserResponse")]
        System.Threading.Tasks.Task<double> DiviserAsync(double nb1, double nb2);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOperationsArithmetiques/Multiplier", ReplyAction="http://tempuri.org/IOperationsArithmetiques/MultiplierResponse")]
        double Multiplier(double nb1, double nb2);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOperationsArithmetiques/Multiplier", ReplyAction="http://tempuri.org/IOperationsArithmetiques/MultiplierResponse")]
        System.Threading.Tasks.Task<double> MultiplierAsync(double nb1, double nb2);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOperationsArithmetiques/EstMultipleDe", ReplyAction="http://tempuri.org/IOperationsArithmetiques/EstMultipleDeResponse")]
        bool EstMultipleDe(int nb1, int nb2);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOperationsArithmetiques/EstMultipleDe", ReplyAction="http://tempuri.org/IOperationsArithmetiques/EstMultipleDeResponse")]
        System.Threading.Tasks.Task<bool> EstMultipleDeAsync(int nb1, int nb2);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOperationsArithmetiques/ChaineDAdditionsEntieres", ReplyAction="http://tempuri.org/IOperationsArithmetiques/ChaineDAdditionsEntieresResponse")]
        int ChaineDAdditionsEntieres(string chaine);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOperationsArithmetiques/ChaineDAdditionsEntieres", ReplyAction="http://tempuri.org/IOperationsArithmetiques/ChaineDAdditionsEntieresResponse")]
        System.Threading.Tasks.Task<int> ChaineDAdditionsEntieresAsync(string chaine);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOperationsArithmetiques/ChaineDAdditionsReelles", ReplyAction="http://tempuri.org/IOperationsArithmetiques/ChaineDAdditionsReellesResponse")]
        double ChaineDAdditionsReelles(string chaine);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOperationsArithmetiques/ChaineDAdditionsReelles", ReplyAction="http://tempuri.org/IOperationsArithmetiques/ChaineDAdditionsReellesResponse")]
        System.Threading.Tasks.Task<double> ChaineDAdditionsReellesAsync(string chaine);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOperationsArithmetiques/ChaineDAdditionsEtDeSoustractionsEnti" +
            "eres", ReplyAction="http://tempuri.org/IOperationsArithmetiques/ChaineDAdditionsEtDeSoustractionsEnti" +
            "eresResponse")]
        int ChaineDAdditionsEtDeSoustractionsEntieres(string chaine);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOperationsArithmetiques/ChaineDAdditionsEtDeSoustractionsEnti" +
            "eres", ReplyAction="http://tempuri.org/IOperationsArithmetiques/ChaineDAdditionsEtDeSoustractionsEnti" +
            "eresResponse")]
        System.Threading.Tasks.Task<int> ChaineDAdditionsEtDeSoustractionsEntieresAsync(string chaine);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOperationsArithmetiques/ChaineDAdditionsEtDeSoustractionsReel" +
            "les", ReplyAction="http://tempuri.org/IOperationsArithmetiques/ChaineDAdditionsEtDeSoustractionsReel" +
            "lesResponse")]
        double ChaineDAdditionsEtDeSoustractionsReelles(string chaine);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOperationsArithmetiques/ChaineDAdditionsEtDeSoustractionsReel" +
            "les", ReplyAction="http://tempuri.org/IOperationsArithmetiques/ChaineDAdditionsEtDeSoustractionsReel" +
            "lesResponse")]
        System.Threading.Tasks.Task<double> ChaineDAdditionsEtDeSoustractionsReellesAsync(string chaine);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOperationsArithmetiques/ChaineDAdditionsEtSoustractionsEtMult" +
            "iplicationsEntieres", ReplyAction="http://tempuri.org/IOperationsArithmetiques/ChaineDAdditionsEtSoustractionsEtMult" +
            "iplicationsEntieresResponse")]
        int ChaineDAdditionsEtSoustractionsEtMultiplicationsEntieres(string chaine);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOperationsArithmetiques/ChaineDAdditionsEtSoustractionsEtMult" +
            "iplicationsEntieres", ReplyAction="http://tempuri.org/IOperationsArithmetiques/ChaineDAdditionsEtSoustractionsEtMult" +
            "iplicationsEntieresResponse")]
        System.Threading.Tasks.Task<int> ChaineDAdditionsEtSoustractionsEtMultiplicationsEntieresAsync(string chaine);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IOperationsArithmetiquesChannel : OC_Calculus_ConsoleClient.OperationsArithmetiquesService.IOperationsArithmetiques, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class OperationsArithmetiquesClient : System.ServiceModel.ClientBase<OC_Calculus_ConsoleClient.OperationsArithmetiquesService.IOperationsArithmetiques>, OC_Calculus_ConsoleClient.OperationsArithmetiquesService.IOperationsArithmetiques {
        
        public OperationsArithmetiquesClient() {
        }
        
        public OperationsArithmetiquesClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public OperationsArithmetiquesClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public OperationsArithmetiquesClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public OperationsArithmetiquesClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public double Plus(double nb1, double nb2) {
            return base.Channel.Plus(nb1, nb2);
        }
        
        public System.Threading.Tasks.Task<double> PlusAsync(double nb1, double nb2) {
            return base.Channel.PlusAsync(nb1, nb2);
        }
        
        public double Moins(double nb1, double nb2) {
            return base.Channel.Moins(nb1, nb2);
        }
        
        public System.Threading.Tasks.Task<double> MoinsAsync(double nb1, double nb2) {
            return base.Channel.MoinsAsync(nb1, nb2);
        }
        
        public double Diviser(double nb1, double nb2) {
            return base.Channel.Diviser(nb1, nb2);
        }
        
        public System.Threading.Tasks.Task<double> DiviserAsync(double nb1, double nb2) {
            return base.Channel.DiviserAsync(nb1, nb2);
        }
        
        public double Multiplier(double nb1, double nb2) {
            return base.Channel.Multiplier(nb1, nb2);
        }
        
        public System.Threading.Tasks.Task<double> MultiplierAsync(double nb1, double nb2) {
            return base.Channel.MultiplierAsync(nb1, nb2);
        }
        
        public bool EstMultipleDe(int nb1, int nb2) {
            return base.Channel.EstMultipleDe(nb1, nb2);
        }
        
        public System.Threading.Tasks.Task<bool> EstMultipleDeAsync(int nb1, int nb2) {
            return base.Channel.EstMultipleDeAsync(nb1, nb2);
        }
        
        public int ChaineDAdditionsEntieres(string chaine) {
            return base.Channel.ChaineDAdditionsEntieres(chaine);
        }
        
        public System.Threading.Tasks.Task<int> ChaineDAdditionsEntieresAsync(string chaine) {
            return base.Channel.ChaineDAdditionsEntieresAsync(chaine);
        }
        
        public double ChaineDAdditionsReelles(string chaine) {
            return base.Channel.ChaineDAdditionsReelles(chaine);
        }
        
        public System.Threading.Tasks.Task<double> ChaineDAdditionsReellesAsync(string chaine) {
            return base.Channel.ChaineDAdditionsReellesAsync(chaine);
        }
        
        public int ChaineDAdditionsEtDeSoustractionsEntieres(string chaine) {
            return base.Channel.ChaineDAdditionsEtDeSoustractionsEntieres(chaine);
        }
        
        public System.Threading.Tasks.Task<int> ChaineDAdditionsEtDeSoustractionsEntieresAsync(string chaine) {
            return base.Channel.ChaineDAdditionsEtDeSoustractionsEntieresAsync(chaine);
        }
        
        public double ChaineDAdditionsEtDeSoustractionsReelles(string chaine) {
            return base.Channel.ChaineDAdditionsEtDeSoustractionsReelles(chaine);
        }
        
        public System.Threading.Tasks.Task<double> ChaineDAdditionsEtDeSoustractionsReellesAsync(string chaine) {
            return base.Channel.ChaineDAdditionsEtDeSoustractionsReellesAsync(chaine);
        }
        
        public int ChaineDAdditionsEtSoustractionsEtMultiplicationsEntieres(string chaine) {
            return base.Channel.ChaineDAdditionsEtSoustractionsEtMultiplicationsEntieres(chaine);
        }
        
        public System.Threading.Tasks.Task<int> ChaineDAdditionsEtSoustractionsEtMultiplicationsEntieresAsync(string chaine) {
            return base.Channel.ChaineDAdditionsEtSoustractionsEtMultiplicationsEntieresAsync(chaine);
        }
    }
}
